//! Sequence storage shared by the matchfinders and the block encoder.

const codes = @import("codes.zig");
const std = @import("std");

/// How matches are searched, from fastest to strongest: the reference
/// encoder's strategies, numbered as it numbers them.
pub const Strategy = enum(u4) {
    fast = 1,
    dfast,
    greedy,
    lazy,
    lazy2,
    btlazy2,
    btopt,
    btultra,
    btultra2,
};

/// One sequence: literals, then a match. `off` is the format's offset
/// value: a repeat code 1-3 or the offset plus 3.
pub const Sequence = struct {
    off: u32,
    /// Literals before the match (the low 16 bits; see `SeqStore.long`).
    lit: u16,
    /// The match length less 3 (low 16 bits).
    ml: u16,
};

/// The distance an offBase refers to in the current repeat history.
pub fn distance(reps: [3]u32, off: u32, zero_literals: bool) u32 {
    if (off > 3) return off - 3;
    const code = off - 1 + @intFromBool(zero_literals);
    return if (code == 3) reps[0] - 1 else reps[code];
}

/// The repeat history after a sequence, using its encoded offset value.
pub fn updateReps(reps: [3]u32, off: u32, zero_literals: bool) [3]u32 {
    if (off > 3) return .{ off - 3, reps[0], reps[1] };
    const code = off - 1 + @intFromBool(zero_literals);
    if (code == 0) return reps;
    return .{ distance(reps, off, zero_literals), reps[0], if (code == 1) reps[2] else reps[1] };
}

/// The sequences of one block and its literals.
pub const SeqStore = struct {
    seqs: []Sequence,
    count: usize = 0,
    lits: []u8,
    lit_len: usize = 0,
    /// The one sequence of a block whose literal or match length does not
    /// fit 16 bits (at most one can, a block being 128 KiB).
    long: ?Long = null,
    ll_codes: []u8,
    ml_codes: []u8,
    of_codes: []u8,

    pub const Long = struct { index: u32, match: bool };

    /// Room for a block of `block` bytes with matches of `min_match` or more.
    pub fn capacity(block: usize, min_match: u32) usize {
        return block / (if (min_match == 3) @as(usize, 3) else 4) + 1;
    }

    pub fn reset(s: *SeqStore) void {
        s.count = 0;
        s.lit_len = 0;
        s.long = null;
    }

    /// A sequence: the literals `in[from..to]`, then a match of
    /// `match_len` with offset value `off`. `limit` is how far `in` may be
    /// read: literals that end 32 bytes before it are copied 16 at a time.
    pub inline fn store(s: *SeqStore, in: []const u8, from: usize, to: usize, limit: usize, off: u32, match_len: usize) void {
        const len = to - from;
        const dst = s.lits[s.lit_len..];
        if (to + 32 <= limit) {
            copy16(dst.ptr, in[from..].ptr);
            var i: usize = 16;
            while (i < len) : (i += 16) copy16(dst.ptr + i, in[from + i ..].ptr);
        } else {
            @memcpy(dst[0..len], in[from..to]);
        }
        s.lit_len += len;
        if (len > 0xffff) s.long = .{ .index = @intCast(s.count), .match = false };
        const ml = match_len - codes.min_match;
        if (ml > 0xffff) s.long = .{ .index = @intCast(s.count), .match = true };
        s.seqs[s.count] = .{ .off = off, .lit = @truncate(len), .ml = @truncate(ml) };
        s.count += 1;
    }

    /// The literals after the last sequence.
    pub fn storeLast(s: *SeqStore, literals: []const u8) void {
        @memcpy(s.lits[s.lit_len..][0..literals.len], literals);
        s.lit_len += literals.len;
    }

    pub fn litLen(s: *const SeqStore, i: usize) u32 {
        const l: u32 = s.seqs[i].lit;
        if (s.long) |long| if (long.index == i and !long.match) return l + 0x10000;
        return l;
    }

    pub fn matchLen(s: *const SeqStore, i: usize) u32 {
        const m: u32 = s.seqs[i].ml;
        if (s.long) |long| if (long.index == i and long.match) return m + 0x10000;
        return m;
    }

    /// A borrowed partition; only the final partition includes trailing
    /// literals. Long sequence lengths keep their partition-relative index.
    pub fn chunk(s: *const SeqStore, from: usize, to: usize) SeqStore {
        var first_lit: usize = 0;
        for (0..from) |i| first_lit += s.litLen(i);
        var last_lit = first_lit;
        for (from..to) |i| last_lit += s.litLen(i);
        if (to == s.count) last_lit = s.lit_len;
        var part = s.*;
        part.seqs = s.seqs[from..to];
        part.count = to - from;
        part.lits = s.lits[first_lit..last_lit];
        part.lit_len = last_lit - first_lit;
        part.ll_codes = s.ll_codes[from..to];
        part.ml_codes = s.ml_codes[from..to];
        part.of_codes = s.of_codes[from..to];
        part.long = if (s.long) |long| if (long.index >= from and long.index < to) .{ .index = @intCast(long.index - from), .match = long.match } else null else null;
        return part;
    }

    /// Regenerated bytes represented by this partition.
    pub fn decodedLen(s: *const SeqStore) usize {
        var len = s.lit_len;
        for (0..s.count) |i| len += s.matchLen(i) + codes.min_match;
        return len;
    }

    /// How often each code occurs.
    pub const Counts = struct {
        ll: [64]u32,
        of: [64]u32,
        ml: [64]u32,
    };

    /// The three codes of every sequence, and their counts (two tables
    /// each, even and odd sequences, so that runs of one code do not wait
    /// on their own increments).
    pub fn toCodes(s: *SeqStore, counts: *Counts) void {
        var c: [2]Counts = .{ std.mem.zeroes(Counts), std.mem.zeroes(Counts) };
        const n = s.count;
        for (s.seqs[0..n], s.ll_codes[0..n], s.ml_codes[0..n], s.of_codes[0..n], 0..) |q, *ll, *ml, *of, i| {
            ll.* = codes.llCode(q.lit);
            ml.* = codes.mlCode(@as(u32, q.ml) + codes.min_match);
            of.* = codes.ofCode(q.off);
            const t = &c[i & 1];
            t.ll[ll.*] += 1;
            t.ml[ml.*] += 1;
            t.of[of.*] += 1;
        }
        if (s.long) |long| {
            const t = &c[long.index & 1];
            if (long.match) {
                t.ml[s.ml_codes[long.index]] -= 1;
                s.ml_codes[long.index] = codes.max_ml;
                t.ml[codes.max_ml] += 1;
            } else {
                t.ll[s.ll_codes[long.index]] -= 1;
                s.ll_codes[long.index] = codes.max_ll;
                t.ll[codes.max_ll] += 1;
            }
        }
        for (0..64) |k| {
            counts.ll[k] = c[0].ll[k] + c[1].ll[k];
            counts.of[k] = c[0].of[k] + c[1].of[k];
            counts.ml[k] = c[0].ml[k] + c[1].ml[k];
        }
    }
};

inline fn copy16(dst: [*]u8, src: [*]const u8) void {
    const v: @Vector(16, u8) = src[0..16].*;
    dst[0..16].* = v;
}
